[package]
name = "yt-search-play"
version = "2.0.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
tempfile = "3"
ctrlc = "3"
anyhow = "1"
which = "7"
ratatui = "0.26"
crossterm = "0.27"

[profile.release]
strip = true
lto = true
codegen-units = 1
